### ISSUE TITLE
app/routes/login.js actually requires a model in order to work.

### ISSUE THREAD

**Issue by twisted1919** [DoryZi/SimpleAuth#2]
This is what worked for me:

```
import Ember from 'ember';

export default Ember.Route.extend({
    model(){
        return {
            "identification": null,
            "password": null
        }
    }
});

```

Otherwise no data is passed from the view to the ajax call. Not sure why is this nor if this the proper way to do it...

Using ember 2.2.0

**Comment by DoryZi** [comment]
@twisted1919 my code was tested using the most recent version of Ember(1.13 / 2)  at the time, as I wrote in my blog post at the top. I suspect that there have been changes for 2.2.2, and that is why some of your code wasn't working. :)
