### ISSUE TITLE
Issues with authorize method, does not get called.

### ISSUE THREAD

**Issue by twisted1919** [DoryZi/SimpleAuth#3]
I think i am missing the point here, but the authorize method from authorizers/custom.js never seems to get called... 

When i am calling a `this.store.findAll('whatever')` shouldn't the Auth header be added to the ajax call? If so, then it is not added at all.

Another use case is for when using Ember.$.ajax, but here again, i am not sure if the header should be added or not, thing is, it isn't and i have to manually add it as in:

```
var authToken = !Ember.isEmpty(that.get('session.data.authenticated.access_token')) ? that.get('session.data.authenticated.access_token') : '';

            var promise = Ember.$.ajax({
                url: ENV.apiServer + '/register',
                type: 'POST',
                contentType : 'application/json',
                dataType : 'json',
                data: JSON.stringify({
                    "first_name": that.get('firstName'),
                    "last_name": that.get('lastName'),
                    "email": that.get('email'),
                    "password": that.get('password'),
                }),
                beforeSend: function(xhr, a){
                    xhr.setRequestHeader('Authorization', 'Bearer ' + authToken);
                },
            });
```

Any idea ?

**Comment by twisted1919** [comment]
Please see https://github.com/simplabs/ember-simple-auth/issues/798

**Comment by DoryZi** [comment]
Hi @twisted1919 Sorry for the delay I was away from the office for a few days. I have used the code, and it did add the auth token, but could have changed as this was last used in Ember(1.13 / 2), which was the latest at the time.  Also could be that they have updated ember-simple-auth. but If you create and register a custom authorizer, then have it's  addHeaderFunction function add whatever you'd like.
That's at least how it worked for me on the above code, that I've actually used..

**Comment by twisted1919** [comment]
@DoryZi - Thanks for the reply, the issue was caused because of the updates the library got recently, but i managed to have it working just like shown in the above link, that is, in case you want to update the code examples :)

**Comment by DoryZi** [comment]
@twisted1919 wish I had the time to do that but I'm at full load, otherwise I'd love to. If you have the time and wish to send an update I'll be happy to do so, otherwise I'll leave it as 1.13 / 2 example, as I suspect newer versions might continue to get updates..Anyhow hope it helped a little at least in getting started :)

**Comment by twisted1919** [comment]
@DoryZi - That helped a lot not just a bit. Thank you ;)

**Comment by DoryZi** [comment]
@twisted1919 I'm so happy to hear that buddy :)
